- enjoytrip_vue/src/components/header/HeaderMenu.vue
- enjoytrip_vue/src/components/hotplace/HotplaceCard.vue
- enjoytrip_vue/src/components/hotplace/HotplaceFeed.vue
- enjoytrip_vue/src/components/myTripPlan/MyTripPlanList.vue
- enjoytrip_vue/src/router/index.js
- enjoytrip_vue/src/views/MyTripPlanView.vue
1. modify hotplace feed padding
2. modify hotplace card grid
> design: hotplace feed padding

- enjoytrip_springboot/src/main/java/com/trip/vue/board/model/service/BoardServiceImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/controller/HotplaceController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/model/dao/HotplaceDao.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/model/service/HotplaceServie.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/model/service/HotplaceServieImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/map/model/service/MapServieImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/controller/PlanController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/service/PlanDetailServiceImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/service/PlanServiceImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/user/controller/UserController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/user/model/service/UserServiceImpl.java
> fix : springboot serviceImpl update

- enjoytrip_vue/src/router/index.js
Fix Router Movement - Reset Scroll Position
> fix : router - scroll position init

- enjoytrip_springboot/src/main/resources/mapper/board-mapping.xml
- enjoytrip_springboot/src/main/resources/mapper/map-mapping.xml
- enjoytrip_vue/src/components/board/BoardDetail.vue
- enjoytrip_vue/src/components/board/BoardModify.vue
- enjoytrip_vue/src/components/hotplace/HotplaceWrite.vue
- enjoytrip_vue/src/components/myTripPlan/MyTripPlanList.vue
1. update board mapper & map mapper
2. fix hotplace write padding
3. bind quill editor with html content
> feat: quill editor binding & springboot mapper update

- enjoytrip_vue/src/assets/css/main.css
design : header nav box-shadow
main.css
```
.cid-uc9QV2Aj9f .navbar-dropdown {
padding: 0;
background-color: #ffffff !important;
position: fixed;
/* header menu 추가 */
box-shadow: 0px -1px 15px 0px #a1a0a0;
}
.cid-uc9QV2Aj9f .opacityScroll {
background: rgba(255, 255, 255, 0) !important;
box-shadow: none;
}
```
> design : header nav box-shadow

- enjoytrip_vue/src/components/user/Login.vue
- enjoytrip_vue/src/components/user/Signup.vue
modify login & signup modal z-index
> design: modify login & signup modal z-index

- enjoytrip_vue/src/components/board/BoardModify.vue
- enjoytrip_vue/src/components/board/BoardWrite.vue
feat: modify board write & modfiy script
> feat: modify board write & modfiy script

- enjoytrip_vue/src/components/hotplace/HotplaceWrite.vue
1. modify feed btn
2. add map on hotplace write page
> design: modify feed btn & feat: add map on hotplace write page

- enjoytrip_springboot/src/main/java/com/trip/vue/board/model/dao/BoardDao.java
- enjoytrip_springboot/src/main/java/com/trip/vue/board/model/service/BoardService.java
- enjoytrip_springboot/src/main/java/com/trip/vue/board/model/service/BoardServiceImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/model/dao/HotplaceDao.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/model/service/HotplaceServie.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/model/service/HotplaceServieImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/map/model/GugunDto.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/controller/PlanController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/dao/PlanDao.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/dao/PlanDetailDao.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/service/PlanDetailService.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/service/PlanDetailServiceImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/service/PlanService.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/service/PlanServiceImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/user/controller/UserController.java
- enjoytrip_springboot/src/main/resources/mapper/board-mapping.xml
- enjoytrip_springboot/src/main/resources/mapper/hotplace-mapping.xml
- enjoytrip_springboot/src/main/resources/mapper/map-mapping.xml
- enjoytrip_springboot/src/main/resources/mapper/plan-mapping.xml
- enjoytrip_springboot/src/main/resources/mapper/planDetail-mapping.xml
- enjoytrip_springboot/src/main/resources/mapper/user-mapping.xml
1. feat : add new mapper for handling hotplace, plan, planDetail
2. fix : update query in existing mapper board, map
> feat & fix: mapper

- enjoytrip_springboot/pom.xml
- enjoytrip_springboot/src/main/java/com/trip/vue/board/controller/BoardController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/model/HotplaceDto.java
- enjoytrip_springboot/src/main/resources/application.properties
- enjoytrip_springboot/src/main/resources/mapper/board-mapping.xml
- enjoytrip_springboot/src/main/resources/mapper/hotplace-mapping.xml
- Changed Blob type handling to byte[] to ensure correct processing in MyBatis.
- Corrected various typos in comments and variable names across the project.
> fix: resolve server startup issues

- enjoytrip_springboot/src/main/resources/db_trip.sql
> docs: database sql

- enjoytrip_springboot/src/main/resources/mapper/board-mapping.xml
fix : mapper board-mapping.xml - query error
- board join user on board.userid = user.userid
> fix : mapper board-mapping.xml - query error

- enjoytrip_vue/src/components/board/BoardDetail.vue
- enjoytrip_vue/src/components/board/BoardModify.vue
- enjoytrip_vue/src/components/board/BoardWrite.vue
- enjoytrip_vue/src/components/hotplace/HotplaceCard.vue
- enjoytrip_vue/src/components/hotplace/HotplaceFeed.vue
- enjoytrip_vue/src/components/hotplace/HotplaceView.vue
- enjoytrip_vue/src/components/user/LoginModal.vue
- enjoytrip_vue/src/components/user/SignupModal.vue
> feat: add hotplace view modal

- enjoytrip_springboot/src/main/resources/mapper/user-mapping.xml
1. add registUser & getTotalUserCount to user-mapping.xml
> docs: add registUser & getTotalUserCount to user-mapping.xml

- enjoytrip_springboot/src/main/java/com/trip/vue/user/controller/UserController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/user/model/service/UserServiceImpl.java
- enjoytrip_springboot/src/main/resources/application.properties
- enjoytrip_springboot/src/main/resources/mapper/user-mapping.xml
1. modify sql mapper 
from resultMap to resultType
> docs: modify sql mapper - resultMap to resultType

- enjoytrip_springboot/src/main/java/com/trip/vue/user/model/service/UserServiceImpl.java
- enjoytrip_springboot/src/main/resources/mapper/user-mapping.xml
1. modify user-mapping.xml variable 
refresh_token to token
> docs: modify user-mapping.xml variable (refresh_token to token)

- enjoytrip_springboot/src/main/java/com/trip/vue/user/controller/UserController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/user/model/service/UserServiceImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/util/JWTUtil.java
- enjoytrip_springboot/src/main/resources/mapper/user-mapping.xml
> docs: modify user-mapping.xml

- enjoytrip_springboot/src/main/java/com/trip/vue/plan/controller/PlanController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/dao/PlanDao.java
- enjoytrip_springboot/src/main/resources/mapper/hotplace-mapping.xml
- enjoytrip_springboot/src/main/resources/mapper/plan-mapping.xml
- enjoytrip_springboot/src/main/resources/mapper/planDetail-mapping.xml
1. fix deleteAllPlanDetail query - param : userid -> delete join plan, plan_days
2. fix deleteAllPlan - param : userid
deleteAllPlanDays query fix - param : userid -> delete join plan
3. remove : hotplace-mapping updateHit query
4. feat : PlanDetail modifyDetailOverview function
5. comment : deleteAllPlan(Days) comment
> feat & fix : springboot controller, mapper.xml

- enjoytrip_springboot/src/main/java/com/trip/vue/map/controller/MapController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/map/model/GugunDto.java
- enjoytrip_springboot/src/main/java/com/trip/vue/map/model/dao/MapDao.java
- enjoytrip_springboot/src/main/java/com/trip/vue/map/model/service/MapService.java
- enjoytrip_springboot/src/main/java/com/trip/vue/map/model/service/MapServiceImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/user/controller/UserController.java
- enjoytrip_springboot/src/main/resources/mapper/map-mapping.xml
> feat: add map rest API

- enjoytrip_springboot/src/main/java/com/trip/vue/map/controller/MapController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/map/model/service/MapServiceImpl.java
deleteAttraction, insertAttraction param
before : @RequestParam("userid") String userid, @RequestParam("content_id") int content_id
after : @RequestParam Map<String, Object> map
> refactory : deleteAttraction, insertAttraction param -> map

- enjoytrip_springboot/src/main/java/com/trip/vue/config/WebConfiguration.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/controller/HotplaceController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/interceptor/JWTInterceptor.java
- enjoytrip_springboot/src/main/java/com/trip/vue/user/controller/UserController.java
- enjoytrip_springboot/src/main/resources/application.properties
- enjoytrip_vue/.env
- enjoytrip_vue/package-lock.json
- enjoytrip_vue/package.json
- enjoytrip_vue/src/api/hotplace.js
- enjoytrip_vue/src/api/user.js
- enjoytrip_vue/src/components/header/HeaderMenu.vue
- enjoytrip_vue/src/components/hotplace/HotplaceCard.vue
- enjoytrip_vue/src/components/hotplace/HotplaceFeed.vue
- enjoytrip_vue/src/components/hotplace/HotplaceViewModal.vue
- enjoytrip_vue/src/components/hotplace/HotplaceWrite.vue
- enjoytrip_vue/src/components/user/MypageInfo.vue
- enjoytrip_vue/src/components/user/MypageModify.vue
- enjoytrip_vue/src/components/user/auth/Login.vue
- enjoytrip_vue/src/components/user/auth/Signup.vue
- enjoytrip_vue/src/main.js
- enjoytrip_vue/src/router/index.js
- enjoytrip_vue/src/stores/hotplace.js
- enjoytrip_vue/src/stores/user.js
- enjoytrip_vue/src/util/http-commons.js
- enjoytrip_vue/src/util/http-status.js
- enjoytrip_vue/src/views/HotplaceView.vue
- enjoytrip_vue/src/views/MypageView.vue
feat: user authentification & mypage & hotplace
> feat: user authentification & mypage & hotplace

- enjoytrip_vue/src/assets/css/main.css
- enjoytrip_vue/src/components/attraction/AttractionMap.vue
- enjoytrip_vue/src/views/AttractionView.vue
fix : remove map_border-radius & background-color
> fix : remove map_border-radius & background-color

- enjoytrip_springboot/src/main/resources/application.properties
- enjoytrip_vue/package-lock.json
- enjoytrip_vue/package.json
- enjoytrip_vue/src/api/user.js
- enjoytrip_vue/src/components/header/HeaderMenu.vue
- enjoytrip_vue/src/components/hotplace/HotplaceCard.vue
- enjoytrip_vue/src/components/hotplace/HotplaceFeed.vue
- enjoytrip_vue/src/components/hotplace/HotplaceViewModal.vue
- enjoytrip_vue/src/components/user/MypageModify.vue
- enjoytrip_vue/src/components/user/auth/Login.vue
- enjoytrip_vue/src/components/user/auth/Signup.vue
- enjoytrip_vue/src/main.js
- enjoytrip_vue/src/stores/hotplace.js
- enjoytrip_vue/src/stores/user.js
> feat: vue - signup api

- enjoytrip_vue/package-lock.json
- enjoytrip_vue/package.json
- enjoytrip_vue/src/components/attraction/PlanDaysDetails.vue
- enjoytrip_vue/src/components/attraction/TripPlanOffCanvas.vue
feat : plan-detail drag and drop
+ chore :  install vue3-smooth-dnd package
> feat : plan-detail drag and drop

- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/controller/HotplaceController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/user/controller/UserController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/user/model/dao/UserDao.java
- enjoytrip_springboot/src/main/java/com/trip/vue/user/model/service/UserService.java
- enjoytrip_springboot/src/main/java/com/trip/vue/user/model/service/UserServiceImpl.java
- enjoytrip_springboot/src/main/resources/mapper/user-mapping.xml
- enjoytrip_vue/package-lock.json
- enjoytrip_vue/src/App.vue
- enjoytrip_vue/src/api/hotplace.js
- enjoytrip_vue/src/api/user.js
- enjoytrip_vue/src/components/hotplace/HotplaceCard.vue
- enjoytrip_vue/src/components/hotplace/HotplaceFeed.vue
- enjoytrip_vue/src/components/hotplace/HotplaceViewModal.vue
- enjoytrip_vue/src/components/user/MypageModify.vue
- enjoytrip_vue/src/components/user/auth/FindPwd.vue
- enjoytrip_vue/src/components/user/auth/Login.vue
- enjoytrip_vue/src/components/user/auth/Signup.vue
- enjoytrip_vue/src/router/index.js
- enjoytrip_vue/src/stores/hotplace.js
- enjoytrip_vue/src/stores/user.js
1. Authentification
2. Hotplace Feed
> feat: Authentification & Hotplace Feed

- enjoytrip_springboot/pom.xml
- enjoytrip_springboot/src/main/java/com/trip/vue/config/MultipartConfiguration.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/controller/HotplaceController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/model/FileInfoDto.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/model/HotplaceDto.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/model/service/HotplaceService.java
- enjoytrip_springboot/src/main/java/com/trip/vue/hotplace/model/service/HotplaceServiceImpl.java
- enjoytrip_vue/src/api/hotplace.js
- enjoytrip_vue/src/components/hotplace/HotplaceCard.vue
- enjoytrip_vue/src/components/hotplace/HotplaceWrite.vue
- enjoytrip_vue/src/stores/hotplace.js
1. design: remove modal-container media query
2. chore: commons-fileupload & commons-io
3. feat: springboot - get MultipartFile & save file]
4. feat: vue - upload hotplace feed API]
5. fix: hotplace - set feed image path]
6. fix: modify image upload path name
7. design: HotplaceWrite.vue - img object-fit & size
> feat: hotplace feed image upload

- enjoytrip_springboot/diagram/insert_sido.sql
- enjoytrip_springboot/src/main/java/com/trip/vue/map/controller/MapController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/map/model/dao/MapDao.java
- enjoytrip_springboot/src/main/java/com/trip/vue/map/model/service/MapService.java
- enjoytrip_springboot/src/main/java/com/trip/vue/map/model/service/MapServiceImpl.java
- enjoytrip_springboot/src/main/resources/mapper/map-mapping.xml
- enjoytrip_vue/src/assets/css/main.css
- enjoytrip_vue/src/components/attraction/AttractionCardItem.vue
- enjoytrip_vue/src/components/attraction/AttractionCardList.vue
- enjoytrip_vue/src/components/attraction/AttractionSearch.vue
- enjoytrip_vue/src/components/attraction/PlanCalendar.vue
- enjoytrip_vue/src/components/attraction/PlanDaysDetailItem.vue
- enjoytrip_vue/src/components/attraction/PlanDaysDetailList.vue
- enjoytrip_vue/src/components/attraction/PlanDurCalendar.vue
- enjoytrip_vue/src/components/attraction/TripPlanOffCanvas.vue
- enjoytrip_vue/src/components/common/VSearchInput.vue
- enjoytrip_vue/src/components/header/HeaderMenu.vue
- enjoytrip_vue/src/main.js
[refactor : Add DB sido, gugun table code=0 row(defalut) - update query mapping]
[feat : btn color props]
[refactor : search Attraction API - mybatis query][design : attraction search page - icon, color, cardList]
[feat : move plan detail between days]
[design : form-control, text input design]
[fix : missing tag]
> feat & refactor : trip maker

- enjoytrip_vue/src/components/hotplace/HotplaceViewModal.vue
- enjoytrip_vue/src/stores/hotplace.js
fix: HotplaceViewModal.vue duplicate info
> fix: HotplaceViewModal.vue duplicate info

- enjoytrip_springboot/src/main/resources/mapper/board-mapping.xml
- enjoytrip_vue/src/App.vue
- enjoytrip_vue/src/api/board.js
- enjoytrip_vue/src/assets/css/theme.css
- enjoytrip_vue/src/components/board/BoardDetail.vue
- enjoytrip_vue/src/components/board/BoardList.vue
- enjoytrip_vue/src/components/board/BoardWrite.vue
- enjoytrip_vue/src/components/hotplace/HotplaceWrite.vue
- enjoytrip_vue/src/components/user/MypageInfo.vue
- enjoytrip_vue/src/components/user/MypageModify.vue
- enjoytrip_vue/src/components/user/auth/FindPwd.vue
- enjoytrip_vue/src/components/user/auth/Signup.vue
- enjoytrip_vue/src/stores/board.js
- enjoytrip_vue/src/stores/user.js
feat: user password not found message
feat: check email validate
feat: vue - board article delte API
fix: board article hit & board list default sort
fix: prevent another user modify article
remove: remove getUserInfo method
remove: remove moveWrite method
remove: remove unnecessary user fields
fix: add router navigation afterEach condition - fix hit update
design: input class form-control border
refactor: refactor profile img preview code
design: modify mypage profile card font weight
> feat & fix: board article delete API & remove getUserInfo method

- enjoytrip_springboot/src/main/java/com/trip/vue/config/WebConfiguration.java
- enjoytrip_springboot/src/main/java/com/trip/vue/interceptor/JWTInterceptor.java
- enjoytrip_springboot/src/main/java/com/trip/vue/map/controller/MapController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/util/JWTUtil.java
- enjoytrip_vue/src/api/attraction.js
- enjoytrip_vue/src/api/hotplace.js
- enjoytrip_vue/src/api/user.js
- enjoytrip_vue/src/components/attraction/PlanDaysDetailList.vue
- enjoytrip_vue/src/components/home/AreaAttraction.vue
- enjoytrip_vue/src/components/home/CountDown.vue
- enjoytrip_vue/src/stores/attraction.js
- enjoytrip_vue/src/stores/hotplace.js
- enjoytrip_vue/src/stores/user.js
- enjoytrip_vue/src/util/http-commons.js
[feat : axois Attraction API][fix : JWT inteceptor]
[feat : axois hotplace API - Totalcnt][feat : axois user API - Totalcnt]
[fix : axois Data loading]
[design : button width]
[fix : JWT interceptor]
> feat & fix : REST API & interceptor

- enjoytrip_vue/src/components/user/MypageInfo.vue
- enjoytrip_vue/src/stores/user.js
feat: use local storage for reload (pinia-plugin-persistedstate)
> feat: use local storage for reload (pinia-plugin-persistedstate)

- enjoytrip_springboot/src/main/java/com/trip/vue/config/WebConfiguration.java
- enjoytrip_springboot/src/main/java/com/trip/vue/interceptor/JWTInterceptor.java
- enjoytrip_vue/src/util/http-commons.js
> remove : jwt Interceptor

- enjoytrip_vue/package-lock.json
- enjoytrip_vue/package.json
- enjoytrip_vue/src/api/plan.js
- enjoytrip_vue/src/assets/css/main.css
- enjoytrip_vue/src/components/hotplace/HotplaceFeed.vue
- enjoytrip_vue/src/components/hotplace/HotplaceViewModal.vue
- enjoytrip_vue/src/components/myTripPlan/MyTripCalendar.vue
- enjoytrip_vue/src/components/myTripPlan/MyTripViewModal.vue
- enjoytrip_vue/src/components/user/MypageInfo.vue
- enjoytrip_vue/src/stores/plan.js
remove: remove rendering loading code
chore: add full-calendar
design: add full-calendar for trip plan in mypage
design: modify prev, next button & day text color
feat: add modal for plan detail view
feat: vue - get trip plan list API
> feat & design: trip plan calendar

- enjoytrip_springboot/diagram/trip_db_sql.sql
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/controller/PlanController.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/dao/PlanDetailDao.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/service/PlanDetailService.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/service/PlanDetailServiceImpl.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/service/PlanServiceImpl.java
- enjoytrip_springboot/src/main/resources/mapper/plan-mapping.xml
- enjoytrip_springboot/src/main/resources/mapper/planDetail-mapping.xml
- enjoytrip_vue/src/api/plan.js
- enjoytrip_vue/src/components/myTripPlan/MyTripCalendar.vue
- enjoytrip_vue/src/components/myTripPlan/MyTripViewModal.vue
- enjoytrip_vue/src/components/myTripPlan/PlanDetailItem.vue
- enjoytrip_vue/src/router/index.js
fix: fix listPlanDetail in planDetail-mapping.xml
feat: vue - delete plan API
feat: springboot - delete plan API
fix: modify auth-login path
feat: vue - delete plan API
design: MyTripViewModal.vue - button click/unclick color
docs: modify PLAN table start/end_date format from TIMESTAMP to DATE]
fix: full calendar - correct error end_date was fast by day
> feat: trip plan delete API

- enjoytrip_vue/src/components/attraction/PlanDaysDetailList.vue
fix : planStore data import  error
> fix : planStore data import error

- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/PlanDto.java
- enjoytrip_springboot/src/main/java/com/trip/vue/plan/model/service/PlanServiceImpl.java
- enjoytrip_vue/src/components/attraction/PlanDaysDetailItem.vue
- enjoytrip_vue/src/components/attraction/PlanDaysDetailList.vue
- enjoytrip_vue/src/components/attraction/TripPlanOffCanvas.vue
- enjoytrip_vue/src/stores/plan.js
[refactor : Change Plan TimeStamp type => Data type]
[fix : fix request data form (plan API)]
> [fix : fix request data form (plan API)]

- enjoytrip_vue/src/components/hotplace/HotplaceViewModal.vue
fix: modify user (userInfo user -> hotplace user)
> fix: modify user (userInfo user -> hotplace user)
